### ISSUE TITLE
Android input type="file" crashes silently with accept options

### ISSUE THREAD

**Issue by DIGITALSQUAD** [react-native-community/react-native-webview#1121]
On Android webview Input type="file" crashes with accept options. 
https://github.com/react-native-community/react-native-webview/issues/787#issuecomment-559510726

Works fine
`<input type="file" name="image">`

Crashes silently
`<input type="file" name="image"  accept=".jpg,.jpeg,.png" >`

React native debugger logs only shows [React DevTools] Connection to RN closed.

**Environment:**
 - OS: Android
 - OS version: 7.0 API 24, 8.0 API 26 and 9.0 API 28
 - react-native version: 0.59.9
 - react-native-webview version: 8.0.2

**Comment by shine1594** [comment]
I have the same issue :(

**Comment by shine1594** [comment]
It works for me to use full mime-type text instead of dot-file-extensions.

**Comment by aza1978** [comment]
@shine1594  - Do you have an example?

**Comment by bengy** [comment]
Using an extension that is unknown to android will cause this crash.
```stacktrace
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
     at com.reactnativecommunity.webview.RNCWebViewModule.isArrayEmpty(RNCWebViewModule.java:387)
     at com.reactnativecommunity.webview.RNCWebViewModule.acceptsImages(RNCWebViewModule.java:283)
     at com.reactnativecommunity.webview.RNCWebViewModule.startPhotoPickerIntent(RNCWebViewModule.java:183)
     at com.reactnativecommunity.webview.RNCWebViewManager$RNCWebChromeClient.onShowFileChooser(RNCWebViewManager.java:1052)
     at Kp.runFileChooser(PG:10)
     at android.os.MessageQueue.nativePollOnce(Native Method)
     at android.os.MessageQueue.next(Unknown Source:17)
     at android.os.Looper.loop(Unknown Source:65)
     at android.app.ActivityThread.main(Unknown Source:98)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
     at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
```

For example using the extension ".testFile" will result in [`acceptsImages`](https://github.com/react-native-community/react-native-webview/blob/b10b97646ba83f492eaf2604a23bf93d34f10560/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java#L301) being called with parameter `types=[".testFile"]`, resulting in
[`getAcceptedMimeType`](https://github.com/react-native-community/react-native-webview/blob/b10b97646ba83f492eaf2604a23bf93d34f10560/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java#L328) being called and returning `[null]`
 ```java
getAcceptedMimeType([".testFile"]) → [null]
```
And then calling [`isArrayEmpty`](https://github.com/react-native-community/react-native-webview/blob/b10b97646ba83f492eaf2604a23bf93d34f10560/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java#L403) with `[null]` and throwing an Exception on `arr[0].length() == 0`

**Comment by aza1978** [comment]
^^ Is this able to be merged into master?

**Comment by lfaz** [comment]
This is still not working for me on Android react-native-webview 11.0, any idea how to fix this?

**Comment by dionisio28** [comment]
Hi @lfaz , did you manage to solve this problem?

**Comment by AlexanderLanderos** [comment]
Yeah same here! 11.0 is dead for us

**Comment by Deibi12** [comment]
any update?

**Comment by mnhoi** [comment]
same me, webview v11.22.7
