### ISSUE TITLE
HTTP Redirect 302 generate Error

### ISSUE THREAD

**Issue by matthieupinte** [react-native-community/react-native-webview#415]
Hi,
Don't know why, but got some issue when WebView call an URL that do a redirect.

- **React** ^16.3.0-alpha.1
- **React Native** 0.53.3
- **React Native Webview** ^5.3.0

Android :
```
compileSdkVersion 26
buildToolsVersion "28.0.3"
...
dependencies {
    compile project(':react-native-webview')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:28.0.0"
    compile "com.android.support:design:28.0.0"
    compile "com.android.support:support-v4:28.0.0"
    ...
```

Here with a **redirect** status **302**, not working:

```js
import React from 'react'
import { WebView } from 'react-native-webview'

export default () => (
  <WebView source={{uri: 'https://httpstat.us/302'}} /> // NOT working
)
```

Red screen :

<img width="352" alt="Screenshot 2019-03-13 at 2 45 53 PM" src="https://user-images.githubusercontent.com/2217014/54283658-c5f7a000-459e-11e9-9af7-e869fc010e21.png">

Stacktrace :

```
03-13 14:44:31.310 12956 12956 I cr_Ime  : ImeThread is enabled.
03-13 14:44:31.317 12956 14948 D EGL_emulation: eglMakeCurrent: 0x94c52040: ver 3 0 (tinfo 0x810b14c0)
03-13 14:44:31.327 12956 12956 E chromium: [ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: Exception in native call
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: com.facebook.react.bridge.NativeArgumentsParseException: TypeError: expected dynamic type `double', but had type `null' (constructing arguments for UIManager.dispatchViewManagerCommand at argument index 0)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:368)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:751)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:154)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:761)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `double', but had type `null'
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeArray.getDouble(Native Method)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:66)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:62)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:361)
03-13 14:44:31.695 12956 21643 E unknown:ReactNative: 	... 8 more
03-13 14:44:31.713 12956 12956 W cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 12956
03-13 14:44:31.827 12956 12956 D ReactNative: CatalystInstanceImpl.destroy() start
03-13 14:44:31.829 12956 12956 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
03-13 14:44:31.834 12956 12956 W unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["onAnimatedValueUpdate",{"value":1,"tag":12}])
03-13 14:44:31.834 12956 12956 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
03-13 14:44:31.834 12956 12956 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
03-13 14:44:31.834 12956 12956 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
03-13 14:44:31.842 12956 12956 W unknown:ReactNative: Calling JS function after bridge has been destroyed: JSTimers.callTimers([[229]])
03-13 14:44:32.089 12956 21640 D ReactNative: CatalystInstanceImpl.destroy() end
```

Here with a **200 OK** status, working well:

```js
import React from 'react'
import { WebView } from 'react-native-webview'

export default () => (
  <WebView source={{uri: 'https://httpstat.us/200'}} /> // working
)
```

**Comment by Titozzz** [comment]
This repo only works with react native 0.57 and above

**Comment by thiswhy** [comment]
I had the same problem , It's hard for me to upgrade the version of react-native
