### ISSUE TITLE
React Native Android app that uses websockets is crashing as webview is not loaded

### ISSUE THREAD

**Issue by cpojer** [react-native-community/react-native-webview#432]
* * *
  This issue was originally created by @bakkiraju as facebook/react-native#21822.
  * * *

  

## Environment
Run `react-native info` in your terminal and paste its contents here.
 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 8.46 GB / 31.81 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
React native app with WebSockets runs fine on Android Virtual Device, but fails with following error message stack trace on physical android device.Not sure why WebView is in the picture here as I dont explicitly use it
anywhere in the code

 " This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.
E/WebViewFactory: Chromium WebView package does not exist"

 "android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed"

Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:319)
at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:383)
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194) 
at android.webkit.CookieManager.getInstance(CookieManager.java:39) 
at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:161) 
at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:59) 
at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:59) 
at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:42) 
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:84) 
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) 
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147) 
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
at java.lang.Thread.run(Thread.java:764) 

## Reproducible Demo
Any React native project using standard out of box websockets.
React native app deployed to device using command
"react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res &&  react-native run-android"

**Comment by joaogarupa** [comment]
still searching for solutions

**Comment by Bardiamist** [comment]
One my user got it.

<details>
<summary>Stack trace</summary>

android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:339)
    at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
    at android.webkit.CookieManager.getInstance(CookieManager.java:47)
    at com.facebook.react.modules.network.c.getCookieManager
    at com.facebook.react.modules.network.c.get
    at okhttp3.JavaNetCookieJar.loadForRequest
    at com.facebook.react.modules.network.l.loadForRequest
    at okhttp3.internal.http.BridgeInterceptor.intercept
    at okhttp3.internal.http.RealInterceptorChain.proceed
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept
    at okhttp3.internal.http.RealInterceptorChain.proceed
    at okhttp3.internal.http.RealInterceptorChain.proceed
    at okhttp3.RealCall.getResponseWithInterceptorChain
    at okhttp3.RealCall$AsyncCall.execute
    at okhttp3.internal.NamedRunnable.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:435)
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
    at android.webkit.CookieManager.getInstance(CookieManager.java:47)
    at com.facebook.react.modules.network.c.getCookieManager
    at com.facebook.react.modules.network.c.get
    at okhttp3.JavaNetCookieJar.loadForRequest
    at com.facebook.react.modules.network.l.loadForRequest
    at okhttp3.internal.http.BridgeInterceptor.intercept
    at okhttp3.internal.http.RealInterceptorChain.proceed
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept
    at okhttp3.internal.http.RealInterceptorChain.proceed
    at okhttp3.internal.http.RealInterceptorChain.proceed
    at okhttp3.RealCall.getResponseWithInterceptorChain
    at okhttp3.RealCall$AsyncCall.execute
    at okhttp3.internal.NamedRunnable.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
</details>

Android 10 Samsung (SM-G980F)

**Comment by Bardiamist** [comment]
What about https://github.com/react-native-community/react-native-webview/issues/14#issuecomment-506610390

**Comment by Bardiamist** [comment]
Found [this answer](https://stackoverflow.com/a/47044644/5507373). Can somebady handle?

**Comment by crazySadSoul** [comment]
still searching for solutions
