### ISSUE TITLE
 The development server returned response error code: 500

### ISSUE THREAD

**Issue by eai301** [react-native-community/react-native-webview#617]
The development server returned response error code: 500

```
URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: jest-haste-map: Haste module naming collision:<br> &nbsp;Duplicate module name: merge<br> &nbsp;Paths: C:\Users\USER\Desktop\AwesomeProject\node_modules___\merge\package.json collides with C:\Users\USER\Desktop\AwesomeProject\node_modules\react-native\Libraries\vendor\core\merge.js<br><br>This error is caused by `hasteImpl` returning the same name for different files.<br> &nbsp; &nbsp;at setModule (C:\Users\USER\Desktop\AwesomeProject\node_modules\jest-haste-map\build\index.js:569:17)<br> &nbsp; &nbsp;at workerReply (C:\Users\eainet\Desktop\AwesomeProject\node_modules\jest-haste-map\build\index.js:641:9)<br> &nbsp; &nbsp;at &lt;anonymous&gt;<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:188:7)</pre>
</body>
</html>

processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:206
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1133
run
    ThreadPoolExecutor.java:607
run
    Thread.java:761
```

my package.json

```
{
  "name": "smh",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-webview": "^5.10.0",
    "react-timer-mixin": "^0.13.4"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "description": "smh fashion lounge",
  "main": "index.js",
  "keywords": [
    "smh",
    "fashion",
    "kuwait"
  ],
  "author": "tnk",
  "license": "ISC"
}

```
screen shot
https://prnt.sc/nwji8t

any one?

**Comment by Titozzz** [comment]
I don't think this error would be related to Webview, please try to isolate your problem by creating a small reproduction. If your issue persists I can reopen this
