### ISSUE TITLE
Android API level 16 crash

### ISSUE THREAD

**Issue by Thomazella** [react-native-community/react-native-webview#723]
**Bug description:**
Crash on android app lauch on API level 16

**To Reproduce:**

Add this package to your react-native-project, build apk, run on emulator using API level 16. Expect crash

**Expected behavior:**
since build.gradle specifies minSdk as 16 I expected this lib to work on API level 16 devices

**Screenshots/Videos:**
![Screen Shot 2019-07-15 at 12 40 28 PM](https://user-images.githubusercontent.com/15015324/61229011-c09d9400-a6fd-11e9-8a06-7969f2e51c8f.png)

```
07-15 12:26:00.632 2613-2613/com.appmobile E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider com.reactnativecommunity.webview.RNCWebViewFileProvider: java.lang.ClassNotFoundException: com.reactnativecommunity.webview.RNCWebViewFileProvider
        at android.app.ActivityThread.installProvider(ActivityThread.java:4563)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)
        at android.app.ActivityThread.access$1300(ActivityThread.java:130)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: com.reactnativecommunity.webview.RNCWebViewFileProvider
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4548)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:130) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4745) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
        at dalvik.system.NativeStart.main(Native Method) 
07-15 12:26:01.162 2284-2284/com.android.launcher E/EGL_emulation: tid 2284: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
07-15 12:26:15.742 2625-2625/com.appmobile E/Trace: error opening trace file: Permission denied (13)
07-15 12:26:15.752 2625-2625/com.appmobile E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider com.reactnativecommunity.webview.RNCWebViewFileProvider: java.lang.ClassNotFoundException: com.reactnativecommunity.webview.RNCWebViewFileProvider
        at android.app.ActivityThread.installProvider(ActivityThread.java:4563)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)
        at android.app.ActivityThread.access$1300(ActivityThread.java:130)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: com.reactnativecommunity.webview.RNCWebViewFileProvider
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4548)
```

**Environment:**
rn info
```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 195.02 MB / 16.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.5.0 - ~/.nvm/versions/node/v12.5.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.5.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.0
      System Images: android-16 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.2 => 0.60.2
```
"react-native-webview": "5.12.1"

**Comment by Thomazella** [comment]
https://github.com/Thomazella/webview-test nevermind, it works with a fresh app. 🤔 I'm open to get some help on this crash though.

**Comment by sohaib-gk** [comment]
Hi, i am still facing this problem.. Any solution for that ?

**Comment by joegichuru** [comment]
i am also facing the same issue on api level 16

**Comment by AmmarRajab** [comment]
how this issue is closed!! .. the crash is still there

**Comment by bbeckk** [comment]
same issue for me too in android older devices only.

**Comment by Hirurgo** [comment]
Android 4.4, error still here

**Comment by bashen1** [comment]
try to modiy the `MainApplication.java`

above RN 0.60
```
import androidx.multidex.MultiDexApplication;

public class MainApplication extends MultiDexApplication implements ReactApplication {
```

and app/bulid.gradle
```
defaultConfig {
        dexOptions{
            javaMaxHeapSize "4g"
            incremental true
        }
        multiDexEnabled true
}
dependencies {
  implementation 'androidx.multidex:multidex:2.0.1'
}
```

**Comment by zzorba** [comment]
Seeing this as well in the android pre-launch report for an API 18 device. Doesn't seem to hit any of the other platforms.

**Comment by datnguyen92** [comment]
Can we reopen this issue? We're also facing the same crash on Android 4.x

**Comment by aknad** [comment]
I've the same problem
My app crashes in the pre-launch test on Android 4.3 and using Genymotion on Android 4.1
It seems to works on Android 4.4

**Comment by CptFabulouso** [comment]
Also experiencing crash on Android 4.3. But reading through [this](https://developer.android.com/studio/build/multidex) it appears it's not a direct issue of this library, but just because of too many dependencies in project. It would explain why the issue is not present in fresh app. So enabling Mutlidex as here https://github.com/react-native-community/react-native-webview/issues/723#issuecomment-557967908 is probably the correct way (or remove dependencies..)
