### ISSUE TITLE
[Android] Crash launch after upgrading RN 0.60

### ISSUE THREAD

**Issue by yelkamel** [react-native-community/react-native-webview#777]
Hello,
After upgrading react native to get it work when build 64Bits (for the last GooglePlay requirement)
I follow the guideline for upgrade, now I'm crashing at start with the following logcat error 
Android application crash on start.

**Logcat**

`7724-7788 E/CrashLogHandler: Stack trace: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/views/webview/ReactWebViewManager;
        at com.planet.planet.MainApplication$1.getPackages(MainApplication.java:53)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:78)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:91)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:80)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
        at com.planet.planet.MainActivity.onCreate(MainActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.views.webview.ReactWebViewManager" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.planet.planet.debug-kl4UVs7kB1DjwIuGzZwG2w==/base.apk", zip file "/data/app/com.planet.planet`

Just in case, regarding org.apache.http.legacy, I added  
`<uses-library android:name="org.apache.http.legacy" android:required="false"/>`
in the AndroidManifest to get react-native-maps work with android 9 (it was working before the upgrade process).

**Environment:**
 - OS: Android
 - OS version: 9 
 - react-native version: ^0.60.4
 - react-native-webview version: ^6.9.0

**Comment by louback-rethink** [comment]
Same issue here

**Comment by louback-rethink** [comment]
I find something, are you using on your implemented code properties like `onLoad`? I exclude these properties and starts to run on Android... Maybe is a problem with import on new version that supports AndroidX.

Hope help you!

**Comment by dbarner1** [comment]
@louback-rethink Were you able to get this to run in RN 60?  I'm finding the peer dependency in package.json makes it not possible to?

**Comment by louback-rethink** [comment]
@dbarner1 Well, I'm using the package version `6.9.0`, and the unique stuff that doesn't work is the props `onLoad` (Android), but I replaced it with `renderLoading and startInLoadingState`, let me know more about your problem and what you want to do... 😄

**Comment by dbarner1** [comment]
How do you get it to work with RN 60?

I'm seeing this in version 6.9's package.json:

"peerDependencies": {
"react": "^16.0",
"react-native": ">=0.57 *<0.60*"
},


- - - - -
Dave Barner
Software Developer
Boston, MA

**Comment by louback-rethink** [comment]
I think that need to be update at package file, anyway, the package still working independent for me.

**Comment by OleksandrKucherenko** [comment]
did you include gradle dependency?

```groovy
/* https://developer.android.com/reference/androidx/webkit/package-summary */
implementation 'androidx.webkit:webkit:1.0.0'
```

**Comment by yelkamel** [comment]
@OleksandrKucherenko  I added this line to my build.gradle I got the same crash.

**Comment by manuhook** [comment]
Same issue only on Android 4.4

**Comment by ldco2016** [comment]
I just began implementation of `"react-native-webview-bridge": "0.40.1",` and got this error:

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/views/webview/ReactWebViewManager;`

**Comment by ahmadalfy** [comment]
I'm having the same issue with no clue how to resolve it.

**Comment by raphaelluiz128** [comment]
It's show in my log while i use react native webview bridge, somenone can adjust it?

**Comment by ahmadalfy** [comment]
@raphaeleidus I ended up using [this package](https://www.npmjs.com/package/react-native-webview) which work the same way (with slight difference in a couple of API methods).

**Comment by raajnadar** [comment]
**Try this method (For android)**

cd into android folder

run `gradlew clean` or `./gradlew clean` according to your OS

Now run `react-native run-android` it worked for me in android.

**Try this method (For ios)**

For iOS try deleting pods folder and `pod install`

**Comment by safaiyeh** [comment]
Can you test if upgrading to the latest version of WebView works? We are currently at v8, the peer dependency issue is no longer there.

**Comment by dbarner1** [comment]
No longer an issue!  Thanks Rajendran and Jason.


- - - - -
Dave Barner
Software Developer
Boston, MA

**Comment by bhaskardabhi** [comment]
Issue is still there. any update?

**Comment by Benzer1406** [comment]
Correct, issue still here.

**Comment by MahmoudShaeer** [comment]
same here :/

**Comment by ShridharMe-Kore** [comment]
> I just began implementation of `"react-native-webview-bridge": "0.40.1",` and got this error:
> 
> `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/views/webview/ReactWebViewManager;`
> 
> Followed the steps here: https://github.com/alinz/react-native-webview-bridge#ios

Did you got solution for this

**Comment by vadim312** [comment]
It is supposed to use latest react-native-webview.
I fixed the crash issue by myself and used it
https://github.com/vadim312/react-native-webview-bridge-rn-latest
