### ISSUE TITLE
Android : File Upload Crash

### ISSUE THREAD

**Issue by aza1978** [react-native-community/react-native-webview#787]
Fatal crash when trying to upload files via webview on android...

Triggering HTML

`<input id="upload" accept=".igc" type="file" name="file" multiple="true">`

> 

2019-08-17 16:55:45.208 3900-3900/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at com.reactnativecommunity.webview.RNCWebViewModule.isArrayEmpty(RNCWebViewModule.java:389)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at com.reactnativecommunity.webview.RNCWebViewModule.acceptsImages(RNCWebViewModule.java:285)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at com.reactnativecommunity.webview.RNCWebViewModule.startPhotoPickerIntent(RNCWebViewModule.java:183)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at com.reactnativecommunity.webview.RNCWebViewManager$RNCWebChromeClient.onShowFileChooser(RNCWebViewManager.java:851)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at ic.a(PG:566)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at Bk.runFileChooser(PG:75)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:336)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at android.os.Looper.loop(Looper.java:174)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7319)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2019-08-17 16:55:45.208 3900-3900/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
`

**Comment by aza1978** [comment]
Also on a side note, uploading files from Drive doesnt seem to work even when changing accept to anything including images etc...

**Comment by xwartz** [comment]
I have the same issue.

```
"react-native-webview": "^3.2.2"
```

**Comment by gavande** [comment]
We are having the same issue on Samsung devices.

**Comment by bLightZP** [comment]
Remove " accept=".igc" " from the form if possible, I'm experiencing similar crashes related to Android WebView.

**Comment by aza1978** [comment]
Unfortunately not an option on this end... should be a fairly simple fix but the android webview seems to be buggy as hell with file upload generally
