### ISSUE TITLE
Crash on 64-bit armv8 device which have Mediatek MT6735P chipset with Cortex-A53 CPU

### ISSUE THREAD

**Issue by el173** [react-native-community/react-native-webview#858]
**Bug description:**
Crash on 64-bit armv8 devices with below stack trace. Checked with few different 
Android System WebView versions including latest beta version (77.0.3865.73). 

```
E/unknown:ReactNative: Exception in native call
    android.content.res.Resources$NotFoundException: String resource ID #0x3040003
        at android.content.res.HwResources.getText(HwResources.java:1287)
        at android.content.res.Resources.getString(Resources.java:431)
        at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:709)
        at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:633)
        at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:685)
        at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:834)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:670)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:605)
        at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:319)
        at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:104)
        at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:271)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:131)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:118)
        at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:115)
        at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:268)
        at android.webkit.WebView.<init>(WebView.java:597)
        at android.webkit.WebView.<init>(WebView.java:531)
        at android.webkit.WebView.<init>(WebView.java:514)
        at android.webkit.WebView.<init>(WebView.java:501)
        at android.webkit.WebView.<init>(WebView.java:491)
        at com.reactnativecommunity.webview.RNCWebViewManager$RNCWebView.<init>(RNCWebViewManager.java:902)
        at com.reactnativecommunity.webview.RNCWebViewManager.createRNCWebViewInstance(RNCWebViewManager.java:154)
        at com.reactnativecommunity.webview.RNCWebViewManager.createViewInstance(RNCWebViewManager.java:160)
        at com.reactnativecommunity.webview.RNCWebViewManager.createViewInstance(RNCWebViewManager.java:104)
        at com.facebook.react.uimanager.ViewManager.createViewInstanceWithProps(ViewManager.java:119)
        at com.facebook.react.uimanager.ViewManager.createViewWithProps(ViewManager.java:66)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:259)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:198)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1036)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1007)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:798)
        at android.view.Choreographer.doCallbacks(Choreographer.java:603)
        at android.view.Choreographer.doFrame(Choreographer.java:571)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5667)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**To Reproduce:**
Create a project with react-native init AwesomeProject --0.60.5
Install the the react-native-webview using [React Native WebView Getting Started Guide](https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md)

**Expected behavior:**

Open the relevant web page in in app web view

**Screenshots/Videos:**

![Screenshot_2019-09-10-15-55-18](https://user-images.githubusercontent.com/9252251/64606731-8b06e580-d3e4-11e9-90f1-9a75dee1a94f.png)

**Environment:**
 - OS: Ubuntu
 - OS version: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
 - react-native version: 0.60.5
 - react-native-webview version: ^7.0.4

**Comment by kckunal2612** [comment]
I have the same issue - but that is occurring on the Android emulator for Android Lollipop (5.1).
It is working fine for Android Marshmallow and upwards.

**Comment by kefyru** [comment]
I have the same issue on physical device with ARM Cortex-A53 (Meizu 15 Lite | Flyme 7.0.1.1G| Android 7.1.2)

**Comment by lawrencewqy** [comment]
+1

**Comment by mikehardy** [comment]
Have you guys seen this? I'm crashing because of it https://issuetracker.google.com/issues/141132133 - it's an underlying androidx.appcompat bug it seems

**Comment by mikehardy** [comment]
In MainActivity, this will probably work around your crash, if you are using androidx.appcompat:appcompat:1.1.0:

```java


    // Workaround appcompat-1.1.0 bug https://issuetracker.google.com/issues/141132133
    @Override
    public void applyOverrideConfiguration(Configuration overrideConfiguration) {
        if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT <= 25) {
            return;
        }
        super.applyOverrideConfiguration(overrideConfiguration);
    }
```

**Comment by el173** [comment]
> In MainActivity, this will probably work around your crash, if you are using androidx.appcompat:appcompat:1.1.0:
> 
> ```java
>     // Workaround appcompat-1.1.0 bug https://issuetracker.google.com/issues/141132133
>     @Override
>     public void applyOverrideConfiguration(Configuration overrideConfiguration) {
>         if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT <= 25) {
>             return;
>         }
>         super.applyOverrideConfiguration(overrideConfiguration);
>     }
> ```

Thanks It's worked.

**Comment by jordanvs** [comment]
Kunal, would this be a fix for the web view, allowing us to upgrade RN ?


Jordan Van Schyndel
Chief Technology Officer
1910 Yonge St. Suite #400
Toronto, ON, M4S 1Z5
1-905-617-2063 | www.paymi.com


On October 22, 2019 at 4:07:03 AM, Hashith Karunarathne (notifications@github.com) wrote:

In MainActivity, this will probably work around your crash, if you are using androidx.appcompat:appcompat:1.1.0:

    // Workaround appcompat-1.1.0 bug https://issuetracker.google.com/issues/141132133
    @Override
    public void applyOverrideConfiguration(Configuration overrideConfiguration) {
        if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT <= 25) {
            return;
        }
        super.applyOverrideConfiguration(overrideConfiguration);
    }
Thanks It's worked.

**Comment by grean** [comment]
@mikehardy Your solution worked
For those how don´t know java well, don't forget to add those imports in order to make the workaround compile.
import android.content.res.Configuration;
import android.os.Build;
