### ISSUE TITLE
Using WebView from more than one process at once with the same data directory is not supported

### ISSUE THREAD

**Issue by mahavirvataliya** [react-native-community/react-native-webview#968]
**Bug description:**
I am getting this error in **Android 9 Samsung Galaxy Note10+** devices with following traces

> java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377

**Stack traces**

> org.chromium.android_webview.AwBrowserProcess.b PG:12
> in.m PG:33
> hn.run PG:2
> org.chromium.base.task.TaskRunnerImpl.g PG:11
> vJ0.run
> android.os.Handler.handleCallback Handler.java:873
> android.os.Handler.dispatchMessage Handler.java:99
> android.os.Looper.loop Looper.java:216
> android.app.ActivityThread.main ActivityThread.java:7263
> java.lang.reflect.Method.invoke Method.java
> com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:494
> com.android.internal.os.ZygoteInit.main ZygoteInit.java:975

**Environment:**
 - OS: Android (Samsung Galaxy Note10+)
 - OS version: 9
 - react-native version: 0.59.10
 - react-native-webview version: 5.10.0

**Comment by ekling** [comment]
Experiencing the same issue for Galaxy devices on Android 9

**Comment by hweister** [comment]
Experiencing the same issue for nubia devices on Android 9

> Fatal Exception: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
       at com.android.webview.chromium.WebViewChromiumAwInit.startChromiumLocked + 63(WebViewChromiumAwInit.java:63)
       at com.android.webview.chromium.WebViewChromiumAwInitForP.startChromiumLocked + 3(WebViewChromiumAwInitForP.java:3)
       at com.android.webview.chromium.WebViewChromiumAwInit$3.run + 3(WebViewChromiumAwInit.java:3)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 215(Looper.java:215)
       at android.app.ActivityThread.main + 7376(ActivityThread.java:7376)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 500(RuntimeInit.java:500)
       at com.android.internal.os.ZygoteInit.main + 865(ZygoteInit.java:865)

**Comment by vovkind** [comment]
Same issue for Galaxy S10e on Android 9
Same RN version: 0.59.10
Same react-native-webview version: 5.10.0

**Comment by hweister** [comment]
Android 9 prohibit sharing WebView data directory among multiple processes
add below code in your mainApplication file
```
public void onCreate() {
        ...
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            String processName = getProcessName(this);
            String packageName = this.getPackageName();
            if (!packageName.equals(processName)) {
                WebView.setDataDirectorySuffix(processName);
            }
        }
}

private String getProcessName(Context context) {
        if (context == null) return null;
        ActivityManager manager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        for (ActivityManager.RunningAppProcessInfo processInfo : manager.getRunningAppProcesses()) {
            if (processInfo.pid == android.os.Process.myPid()) {
                return processInfo.processName;
            }
        }
        return null;
    }
```

**Comment by bashen1** [comment]
Same issue

**Comment by cmcrcruces** [comment]
Same issue here... I'm getting the following:
11:29 AM
14 Nov 13:28 on app version 10030
Samsung Galaxy Note10 (d1), Android 9
Report 1 of 1
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3163)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3306)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1994)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7263)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
Caused by: java.lang.RuntimeException: 
  at org.apache.cordova.CordovaWebViewImpl.createEngine (CordovaWebViewImpl.java:82)
  at org.apache.cordova.CordovaActivity.makeWebViewEngine (CordovaActivity.java:206)
  at org.apache.cordova.CordovaActivity.makeWebView (CordovaActivity.java:202)
  at org.apache.cordova.CordovaActivity.init (CordovaActivity.java:146)
  at org.apache.cordova.CordovaActivity.loadUrl (CordovaActivity.java:224)
  at com.bendigobank.mobileios.BendigoInvestDirect.MainActivity.onCreate (MainActivity.java:39)
  at android.app.Activity.performCreate (Activity.java:7353)
  at android.app.Activity.performCreate (Activity.java:7344)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1275)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3143)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Constructor.newInstance0 (Native Method)
  at java.lang.reflect.Constructor.newInstance (Constructor.java:343)
  at org.apache.cordova.CordovaWebViewImpl.createEngine (CordovaWebViewImpl.java:80)
Caused by: java.lang.RuntimeException: 
  at org.chromium.android_webview.AwBrowserProcess.b (PG:12)
  at in.m (PG:33)
  at in.a (PG:48)
  at in.b (PG:16)
  at com.android.webview.chromium.WebViewChromiumFactoryProvider.a (PG:32)
  at com.android.webview.chromium.WebViewChromium.init (PG:12)
  at android.webkit.WebView.<init> (WebView.java:678)
  at android.webkit.WebView.<init> (WebView.java:604)
  at android.webkit.WebView.<init> (WebView.java:587)
  at android.webkit.WebView.<init> (WebView.java:574)
  at org.apache.cordova.engine.SystemWebView.<init> (SystemWebView.java:47)
  at org.apache.cordova.engine.SystemWebView.<init> (SystemWebView.java:43)
  at org.apache.cordova.engine.SystemWebViewEngine.<init> (SystemWebViewEngine.java:76)

**Comment by cmcrcruces** [comment]
I'm having the same issue...

**Comment by Android-yang** [comment]
I'm having the same issue...

**Comment by dmarkowski** [comment]
Same issue here

**Comment by rgoksu91** [comment]
same issue..

**Comment by sislovesmedotcom** [comment]
+1

**Comment by Daha62** [comment]
same

**Comment by thesourav123** [comment]
same

**Comment by mianaliasjad** [comment]
> Android 9 prohibit sharing WebView data directory among multiple processes
> add below code in your mainApplication file
> 
> ```
> public void onCreate() {
>         ...
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
>             String processName = getProcessName(this);
>             String packageName = this.getPackageName();
>             if (!packageName.equals(processName)) {
>                 WebView.setDataDirectorySuffix(processName);
>             }
>         }
> }
> 
> private String getProcessName(Context context) {
>         if (context == null) return null;
>         ActivityManager manager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
>         for (ActivityManager.RunningAppProcessInfo processInfo : manager.getRunningAppProcesses()) {
>             if (processInfo.pid == android.os.Process.myPid()) {
>                 return processInfo.processName;
>             }
>         }
>         return null;
>     }
> ```

API 28 onwards there is a new api to get process name which is more performant. Check [here](https://developer.android.com/reference/android/app/Application.html#getProcessName())

**Comment by SilverInfinity** [comment]
can anyone confirm or deny if @hweister 's suggestion works?

Seeing this issue in our production application in crashlytics, but I'm unable to get my hands on any devices where its happening. It seems to be happening only on certain new Samsung devices on android 9 and 10. Samsung Galaxy Note10+, S10+, S10, Note9, S9. No reports of it happening on any other devices running android 9 or 10, Nor can I reproduce on any device i have available.

**Comment by MadeinFrance** [comment]
Same bug on OnePlus 7 Pro - Android 10.

Unfortunately the suggestion of @hweister did not work.

**Comment by dev071089** [comment]
Same bug on Oppo device too...

And yes the suggestion of @hweister did not work for me as well.

**Comment by Zestinc** [comment]
Having the same problem.

**Comment by ivorsliide** [comment]
This issue still happening, can we reopen it?

**Comment by AdrianaCarelli** [comment]
Having the same problem with android 10

**Comment by songxiaoliang** [comment]
Having the same problem.

**Comment by jenthone** [comment]
We can refer from this: https://bugs.chromium.org/p/chromium/issues/detail?id=558377#c126

**Comment by Go-Jeon-Pa** [comment]
Is this a WebView bug?

**Comment by ehqwang** [comment]
Experiencing the same issue for xiaomi Max devices on Android 10，

**Comment by GuiOliveiraInfoglobo** [comment]
Having the same issue here

**Comment by Duna** [comment]
```
Fatal Exception: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.dunatv.photosafe (pid 10634), lock owner com.dunatv.foregroundservice (pid 10308)
       at org.chromium.android_webview.AwDataDirLock.b(AwDataDirLock.java:28)
       at hv.i(hv.java:31)
       at gv.run(gv.java:2)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by Noltibus** [comment]
> ```
> Fatal Exception: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.dunatv.photosafe (pid 10634), lock owner com.dunatv.foregroundservice (pid 10308)
>        at org.chromium.android_webview.AwDataDirLock.b(AwDataDirLock.java:28)
>        at hv.i(hv.java:31)
>        at gv.run(gv.java:2)
>        at android.os.Handler.handleCallback(Handler.java:907)
>        at android.os.Handler.dispatchMessage(Handler.java:105)
>        at android.os.Looper.loop(Looper.java:216)
>        at android.app.ActivityThread.main(ActivityThread.java:7625)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
> ```
> 
> Android 9 Honor 9i

Have the exact same issue, while using react but no WebView explicitly

**Comment by Jennyxiav2** [comment]
> can anyone confirm or deny if @hweister 's suggestion works?
> 
> Seeing this issue in our production application in crashlytics, but I'm unable to get my hands on any devices where its happening. It seems to be happening only on certain new Samsung devices on android 9 and 10. Samsung Galaxy Note10+, S10+, S10, Note9, S9. No reports of it happening on any other devices running android 9 or 10, Nor can I reproduce on any device i have available.
> 
> edit:
> To my knowledge, we are not using multiple processes in the application? It seems odd to me that we would only see it on Samsung.
> 
> relevant packages including all libraries that reference importing from android.webkit:
> 
> ```
> react-native: 0.59.10,
> wix/react-native-navigation, // [v1] of the library
> react-native-webview,
> react-native-device-info,
> react-native-fs,
> react-native-image-picker,
> ```

Did you find anything useful? I'm facing the same issue on Samsung...
We are not using multiple processes either, so I don't think 'setDataDirectorySuffix' is a good way to solve it.

**Comment by ysxlmk** [comment]
Having the same problem.

**Comment by parasgupta93** [comment]
Anyone got the solution ??

**Comment by wuyan93** [comment]
java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
	at org.chromium.android_webview.AwBrowserProcess.a(PG:40)
	at ku.c(PG:90)
	at ky.run(PG:3)
	at org.chromium.base.task.TaskRunnerImpl.d_(PG:50)
	at EQ.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

Android 10,level 29    HuaWei/EMOTION

**Comment by bunny-pu** [comment]
Having the same problem

**Comment by kaichunlin** [comment]
I had encountered the same issue in my previous work, where the app runs on a Cordova derivative.
My solution was very similar to @hweister except that:
 - a random number is generated as the suffix
 - a background thread was spawned to delete any old directories

The crashes mostly stopped after releasing this necessary hack.

**Comment by qusai95** [comment]
you can show this link to get more details 
https://blog.katastros.com/a?ID=01600-3fade614-39a4-4b34-bd09-da94047b1e0d

**Comment by ralesiupgrade** [comment]
> Android 9 prohibit sharing WebView data directory among multiple processes add below code in your mainApplication file
> 
> ```
> public void onCreate() {
>         ...
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
>             String processName = getProcessName(this);
>             String packageName = this.getPackageName();
>             if (!packageName.equals(processName)) {
>                 WebView.setDataDirectorySuffix(processName);
>             }
>         }
> }
> 
> private String getProcessName(Context context) {
>         if (context == null) return null;
>         ActivityManager manager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
>         for (ActivityManager.RunningAppProcessInfo processInfo : manager.getRunningAppProcesses()) {
>             if (processInfo.pid == android.os.Process.myPid()) {
>                 return processInfo.processName;
>             }
>         }
>         return null;
>     }
> ```

This worked for me, but i had to make sure it was the first thing called in onCreate, once i moved it around in the method it worked fine. Thanks

**Comment by baptistecassar** [comment]
Hi, I am faced with the same issue. If you have a proper work around could you provide us a snippet in your documentation ?
Thanks

**Comment by nihp** [comment]
I am also facing the same error

**Comment by justindi15** [comment]
Having same error still

**Comment by maxymczech** [comment]
Same here. This error started happenning after adding `react-native-background-geolocation`.

**Comment by jackkinsella** [comment]
Same issue today when using

```
```

**Comment by Sumit-Budhiraja** [comment]
Still facing this issue again.?
Anyone got any fixes on this one.?

**Comment by AkshayOptimumbrew** [comment]
I am facing the same issue with Android.
Device: Huawei Y9 Prime 2019
Android OS: 10
![image](https://github.com/react-native-webview/react-native-webview/assets/98881383/2bdb1e1c-fde5-4a53-8197-9cf17f667561)

**Comment by DisciplineBK** [comment]
me too, 
I have same issue on my service

![스크린샷 2024-04-05 오후 2 14 28](https://github.com/react-native-webview/react-native-webview/assets/57582914/778a6262-23ff-4456-8518-2acb53f36715)

**Comment by maxymczech** [comment]
@hweister Would you be so king to rewrite your fix in Kotlin? 😅 I am trying to upgrade an app I am working on to RN 0.73, the Upgrade Helper tells me to convert MainActivity from Java to Kotlin, and this fix of yours is the last missing piece. Thank you in advance.
