### ISSUE TITLE
String resource id #0x204003

### ISSUE THREAD

**Issue by stempest0925** [react-native-community/react-native-webview#983]
![G$8HG5TK {V%U)$H5SRI2BV](https://user-images.githubusercontent.com/38375917/67554901-d716ab00-f742-11e9-83f3-095280e5b2f9.png)
![DLR1LD(9N4VKL35_1IFKBT6](https://user-images.githubusercontent.com/38375917/67554909-da119b80-f742-11e9-9716-b79249c26d60.png)

The new project has encountered this problem. The RN version fallback is 0.65, and the WebView fallback is 7.0.1, which has no effect. If it is used, an error will be reported. What's the problem? Thank you

**Comment by stempest0925** [comment]
After my test, it's OK on the mobile phone, but it will be like this in the simulator.

**Comment by leonardofalk** [comment]
I can confirm this after upgrading to react-native 0.61.2, it was running fine using 0.60.5. I think this is related to android `string/res/*` folder or some bad reference to it, but I couldn't find what the problem was.

**Comment by Manigandan-Azure** [comment]
@react-native-community-bot @stempest0925 any update on this issue?

**Comment by 00-00-00** [comment]
Having the same issue on react-native `0.59.0`

```
Fatal Exception: android.content.res.Resources$NotFoundException: String resource ID #0x2040002
       at android.content.res.Resources.getText(Resources.java:307)
       at android.content.res.Resources.getString(Resources.java:405)
       at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:702)
       at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
       at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:619)
       at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:758)
       at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:608)
       at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:546)
       at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
       at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:97)
       at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:124)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:111)
       at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:108)
       at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
       at android.webkit.WebView.<init>(WebView.java:580)
       at android.webkit.WebView.<init>(WebView.java:515)
       at android.webkit.WebView.<init>(WebView.java:498)
       at android.webkit.WebView.<init>(WebView.java:485)
       at android.webkit.WebView.<init>(WebView.java:475)
       at com.reactnativecommunity.webview.RNCWebViewManager$RNCWebView.<init>(RNCWebViewManager.java:802)
       at com.reactnativecommunity.webview.RNCWebViewManager.createRNCWebViewInstance(RNCWebViewManager.java:145)
       at com.reactnativecommunity.webview.RNCWebViewManager.createViewInstance(RNCWebViewManager.java:151)
       at com.reactnativecommunity.webview.RNCWebViewManager.createViewInstance(RNCWebViewManager.java:98)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:47)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:256)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:798)
       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
       at android.view.Choreographer.doFrame(Choreographer.java:571)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
```

**Comment by leonardofalk** [comment]
After investigating a while I've noticed its not a bug with react-native-webview but android's webview instead. I think the root of the problem is that it requires bluetooth, but emulators doesn't support it. However using Android 8 emulator works fine (also add bluetooth permissions: https://developer.android.com/guide/topics/connectivity/bluetooth#Permissions).

On Android 5 and 6 it doesn't work just by adding bluetooth permissions, you'll get a `BluetoothAdapter: Bluetooth binder is null` error instead.

**Comment by 00-00-00** [comment]
Downgrading `androidx.appcompat:appcompat` library from `1.1.0` to `1.0.2` solved the issue for me.

**Comment by grean** [comment]
This workaround worked for me : 
https://github.com/react-native-community/react-native-webview/issues/858

**Comment by Valentine-Velugo** [comment]
The issue there is still in the current release.

**Comment by conanma** [comment]
still alive
